language: node_js
branches:
  only:
  - master
  - dev
node_js:
- stable
after_success: npm run coverage && ./scripts/merge_dev_with_master.sh
sudo: false
deploy:
  provider: heroku
  app: offshop-front-end
  on: master
  api_key:
    secure: sQAIB871eE1JjWA0F7MXWFgam97H83YLIoTt0j9vCby8s9eoudKKCsU0GyPDlbJ4bErnVBtlo/G0orFEJkoNpoJzyxarOJYfh4Mhhf5jq4KkbRGzdvMOKndxW147z/pHfXXpluSn49ElXrfsntfz0wrgOP+huJqbL1e75mlgQGkiIgTCyPwNjjwhhI+rG4l6GhOsXgg1d3i+oVpc8HEX6B41/L62ejz4Gf+ht0eWom/UptKvLTu0tIm5jJPTEIQG4Tw1A2N9wGg1QhTklL/c2ooIvY3l8kMGVjAybRYjMvTCKo0T0BdZ/YgYdkImzl+wr+kY0X241gnfVcdKiYQDQkOBeSGKo6w+7evRWbgZh4ySbKDgSfVMubQiQJO5PVIzlFaCey03TO+mE8BX5aGlk0PSFIXU32QHvSBOaxrJdeqUg8iFlaK8+XDYM3txVMtl3AqoDLJMeeH47Q6pdf5el5hmXI7Kqte5jw2auylWjyTpYO5z0co8aaHLgvPlAZQ6leh5Jj9eahkFT1/Z4FTtgas9z/afhjQ/YAqDi7jyPF1elBNNbll7OTfyYj1b6pXrhytgYHL3hI3VEbBOC1oKBMVrVEq5cyw763mZ1Ls/ajfVLfG7yS/K5YaRkj0Pzbv+y5YjbWDuecKDLuJC/quRDbo5SeLiyLgob+PlEOP+6IM=
env:
  global:
    secure: ScfQ8cJAy1CwfOlVToSG92By4zSKhh0yeNoJAcjLecHVTTvo7HD7r5fJ5wK0cI4Wl1sWOnJ0RSksWfiEb2+jehEwdUiuxL8rmtiLR1iPy93KkCtgkzPjJlpi1nF/uhppHFvXti2iGThkeuw3x521f/mYaOW0t4wW24ue3T3vkk7OholOCYdelsvaflZuVjac5sj7i4WjDJ9gquR1OxJh8yz9+iONQIIckeIPHi8xVe2dsMuUtWmvIAsKs98PqSi4VrpY6a94DS8r++fRSdNU/PzVvv8UJePuqhXSBHtqU94OkGXN0vnumDc5NSZERBTi/UEL1HF3Yb/OEHhZUDwz7bsHx18J/EliMp2NmX2izZIxwBD72fEtn21mf0jJOmSlqdZG4qpL10oZpMe09kqrd1zysXwsEN5u6MCxEctrj++vp5npzFO/heUB+hP1Lxxwxqb4syoxgVl04Qb1TYDabS6obNp1fHB35xycix6eITomW+ZpG1KsQn8RhIqKFodNXOPDBW0xHr0JKO7vEydUsU/2KdEUKRrTI0we6bxFrjv28FifxqdkJwZobxT9tlj57QQNcsomFUzAKFZrzJuIESM2OfSMeqhiHDcv8OB4nw0yv68m0txW95yF3NHJSg16Am+s/6HK8foLenG0bvTFnT8xljT+H/iKs1N3B/JebYY=
