language: node_js
branches:
  only:
  - master
  - dev
node_js:
- stable
after_success: npm run coverage && ./scripts/merge_dev_with_master.sh
sudo: false
deploy:
  provider: heroku
  app: offshop-front-end
  on: master
  api_key:
    secure: p1eOr4Vm5SD3cP+0cVmdsm8MDkPqjfAbONUUStfSlCp32CZCltH+XGhIbksvp3bfhPqm8IDlt4oqUaKQNNUh2T2XxHQujFa4T9lUKiIt56rZPCMb9C6F3fssRvyBi51fGmRpl+cUG4e5bRr+tCgZHet9iehjB2+9sNPRnvz63wNzMtVN4U4dLrIlTWnb18mCQc9ZyvCNWCUongYLXBcZ2lCNuZD8virNP9PI9ELvT04c702MG2FaK/fdryURGVg5VmrNQmfQopnvZyXct/NEK5pLDSy9QsLAXEON1gYK8zECyWQHxXd2SXgbPckVFg4gNi8DXveuyHEkUl6uSoY4LpQH25oyW9yQJc4+Q8L/SEhqI1wiTVVrGOgrxtmie15qxhGpPRrCvKwXRyMrohwnHvy2T3vgPNZRDiqCpvoXLfgNtRMZqAFBQYf8Cnk9RKHhIuAM8kn9fXZUb7cH2FgVvrgGClCrdb0fJ5bu6MZNW1TaRynJ7D4Hr3rDIvlJu7wovFDJX3YVeb29hie9wKkVEmvHO2q+HtTXxC2NoA0/4jVTjmhwBvvT4SVZTKwS2IfZoEbMhzretPtr4uCiYM3rU6p+2TO649bMYhAdkDwkMSOfBYjWFek/IOSg/5Y7me6C9iyKjrbQ3uq2xagZCu0i4rLI5fGwgYgg6uw8e5t1CWM=
env:
  global:
    secure: ScfQ8cJAy1CwfOlVToSG92By4zSKhh0yeNoJAcjLecHVTTvo7HD7r5fJ5wK0cI4Wl1sWOnJ0RSksWfiEb2+jehEwdUiuxL8rmtiLR1iPy93KkCtgkzPjJlpi1nF/uhppHFvXti2iGThkeuw3x521f/mYaOW0t4wW24ue3T3vkk7OholOCYdelsvaflZuVjac5sj7i4WjDJ9gquR1OxJh8yz9+iONQIIckeIPHi8xVe2dsMuUtWmvIAsKs98PqSi4VrpY6a94DS8r++fRSdNU/PzVvv8UJePuqhXSBHtqU94OkGXN0vnumDc5NSZERBTi/UEL1HF3Yb/OEHhZUDwz7bsHx18J/EliMp2NmX2izZIxwBD72fEtn21mf0jJOmSlqdZG4qpL10oZpMe09kqrd1zysXwsEN5u6MCxEctrj++vp5npzFO/heUB+hP1Lxxwxqb4syoxgVl04Qb1TYDabS6obNp1fHB35xycix6eITomW+ZpG1KsQn8RhIqKFodNXOPDBW0xHr0JKO7vEydUsU/2KdEUKRrTI0we6bxFrjv28FifxqdkJwZobxT9tlj57QQNcsomFUzAKFZrzJuIESM2OfSMeqhiHDcv8OB4nw0yv68m0txW95yF3NHJSg16Am+s/6HK8foLenG0bvTFnT8xljT+H/iKs1N3B/JebYY=
