export const RETRIEVE_ADMIN_DELIVERY_METHOD_REQUEST = 'RETRIEVE_ADMIN_DELIVERY_METHOD_REQUEST';
export const RETRIEVE_ADMIN_DELIVERY_METHOD_SUCCESS = 'RETRIEVE_ADMIN_DELIVERY_METHOD_SUCCESS';
export const RETRIEVE_ADMIN_DELIVERY_METHOD_FAILURE = 'RETRIEVE_ADMIN_DELIVERY_METHOD_FAILURE';

export const CREATE_DELIVERY_METHOD_REQUEST = 'CREATE_DELIVERY_METHOD_REQUEST';
export const CREATE_DELIVERY_METHOD_SUCCESS = 'CREATE_DELIVERY_METHOD_SUCCESS';
export const CREATE_DELIVERY_METHOD_FAILURE = 'CREATE_DELIVERY_METHOD_FAILURE';

export const UPDATE_DELIVERY_METHOD_REQUEST = 'UPDATE_DELIVERY_METHOD_REQUEST';
export const UPDATE_DELIVERY_METHOD_SUCCESS = 'UPDATE_DELIVERY_METHOD_SUCCESS';
export const UPDATE_DELIVERY_METHOD_FAILURE = 'UPDATE_DELIVERY_METHOD_FAILURE';

export const RESET_DELIVERY_METHOD = 'RESET_DELIVERY_METHOD';

export const RETRIEVE_ADMIN_DELIVERY_METHODS_REQUEST = 'RETRIEVE_ADMIN_DELIVERY_METHODS_REQUEST';
export const RETRIEVE_ADMIN_DELIVERY_METHODS_SUCCESS = 'RETRIEVE_ADMIN_DELIVERY_METHODS_SUCCESS';
export const RETRIEVE_ADMIN_DELIVERY_METHODS_FAILURE = 'RETRIEVE_ADMIN_DELIVERY_METHODS_FAILURE';

export const DELETE_DELIVERY_METHOD_REQUEST = 'DELETE_DELIVERY_METHOD_REQUEST';
export const DELETE_DELIVERY_METHOD_SUCCESS = 'DELETE_DELIVERY_METHOD_SUCCESS';
export const DELETE_DELIVERY_METHOD_FAILURE = 'DELETE_DELIVERY_METHOD_FAILURE';
export const RETRIEVE_DELIVERY_METHODS_REQUEST = 'RETRIEVE_DELIVERY_METHODS_REQUEST';
export const RETRIEVE_DELIVERY_METHODS_SUCCESS = 'RETRIEVE_DELIVERY_METHODS_SUCCESS';
export const RETRIEVE_DELIVERY_METHODS_FAILURE = 'RETRIEVE_DELIVERY_METHODS_FAILURE';
export const SET_CURRENT_DELIVERY_METHOD= 'SET_CURRENT_DELIVERY_METHOD';
export const SYNC_DELIVERY_METHODS = 'SYNC_DELIVERY_METHODS';
export const ON_CREATE_DELIVERY_METHOD = 'ON_CREATE_DELIVERY_METHOD';
export const ON_UPDATE_DELIVERY_METHOD = 'ON_UPDATE_DELIVERY_METHOD';
export const ON_DELETE_DELIVERY_METHOD = 'ON_DELETE_DELIVERY_METHOD';