export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREMENT_IN_CART = 'DECREMENT_IN_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const ON_UPDATE_PRODUCT_IN_CART = 'ON_UPDATE_PRODUCT_IN_CART';
export const ON_DELETE_PRODUCT_IN_CART = 'ON_DELETE_PRODUCT_IN_CART';
