describe('App initialization', () => {
    it('Displays products from API on load', () => {
        cy.server();
        cy.route('GET', '/products', [
            {
                active: true,
                categoryId: null,
                createdAt: "2018-12-27T14:30:46.101Z",
                img: "stroik_4.jpg",
                inCart: 0,
                name: "Stroik 4",
                price: 80,
                quantity: 1,
                slug: "stroik-4",
                unit: "kg",
                unitPrice: 80,
                unitsPerProduct: 1,
                updatedAt: "2018-12-27T14:30:46.101Z",
                __v: 0,
                _id: "5c24e216bfa8e2a4369bf677",
            },
            {
                active: true,
                categoryId: null,
                createdAt: "2018-12-27T14:29:06.306Z",
                img: "stroik_3.jpg",
                inCart: 0,
                name: "Stroik 3",
                price: 55,
                quantity: 3,
                slug: "stroik-3",
                unit: "kg",
                unitPrice: 55,
                unitsPerProduct: 1,
                updatedAt: "2018-12-27T14:29:06.306Z",
                __v: 0,
                _id: "5c24e1b2bb1356a4267fd7e2",
            },
            {
                active: true,
                categoryId: null,
                createdAt: "2018-12-27T14:28:06.533Z",
                img: "stroik_2.jpg",
                inCart: 0,
                name: "Stroik 2",
                price: 25,
                quantity: 5,
                slug: "stroik-2",
                unit: "kg",
                unitPrice: 25,
                unitsPerProduct: 1,
                updatedAt: "2018-12-27T14:28:06.533Z",
                __v: 0,
                _id: "5c24e17695e643a40f3fc2a2",
            },
            {
                active: true,
                categoryId: null,
                createdAt: "2018-12-27T14:26:34.262Z",
                img: "stroik_1.jpg",
                inCart: 0,
                name: "Stroik 1",
                price: 35,
                quantity: 2,
                slug: "stroik-1",
                unit: "kg",
                unitPrice: 35,
                unitsPerProduct: 1,
                updatedAt: "2018-12-27T14:26:34.262Z",
                __v: 0,
                _id: "5c24e11a95e643a40f3fc2a1",
            }
        ]);
        cy.visit('/');
    });
});