export const STEP_NEXT = 'STEP_NEXT';
export const STEP_BACK = 'STEP_BACK';
export const SET_ACTIVE_STEP_ID = 'SET_ACTIVE_STEP_ID';
export const SET_BUYER_INPUT_VALUE = 'SET_BUYER_INPUT_VALUE';
export const SET_BUYER_DELIVERY_INPUT_VALUE = 'SET_BUYER_DELIVERY_INPUT_VALUE';
